# Generated by Django 6.0.3 on 2026-04-08 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('specialization', models.CharField(blank=True, default='', max_length=255, verbose_name='Специализация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='idx_trainers_last_first')],
            },
        ),
        migrations.CreateModel(
            name='TrainerWorkSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Начало')),
                ('end_datetime', models.DateTimeField(verbose_name='Окончание')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для записи')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_slots', to='trainers.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Рабочий слот тренера',
                'verbose_name_plural': 'Рабочие слоты тренеров',
                'ordering': ['start_datetime'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='chk_trainer_work_slots_time')],
            },
        ),
    ]
