# Generated by Django 6.0.3 on 2026-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Срок действия (дни)')),
                ('visit_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит посещений')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'План абонемента',
                'verbose_name_plural': 'Планы абонементов',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='chk_membership_plans_duration'), models.CheckConstraint(condition=models.Q(('visit_limit__isnull', True), ('visit_limit__gt', 0), _connector='OR'), name='chk_membership_plans_visit_limit')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('service_type', models.CharField(choices=[('group', 'Групповое занятие'), ('individual', 'Индивидуальное занятие')], max_length=20, verbose_name='Тип услуги')),
                ('default_duration_minutes', models.PositiveIntegerField(verbose_name='Длительность по умолчанию (мин)')),
                ('default_capacity', models.PositiveIntegerField(default=1, verbose_name='Вместимость по умолчанию')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('default_duration_minutes__gt', 0)), name='chk_services_duration'), models.CheckConstraint(condition=models.Q(('default_capacity__gt', 0)), name='chk_services_capacity')],
            },
        ),
    ]
