# Generated by Django 6.0.3 on 2026-04-08 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Количество мест')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Проведено'), ('canceled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='services.service', verbose_name='Услуга')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='trainers.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Записан'), ('visited', 'Посетил'), ('canceled', 'Отменена'), ('missed', 'Не пришел')], default='booked', max_length=20, verbose_name='Статус')),
                ('canceled_by', models.CharField(blank=True, choices=[('client', 'Клиент'), ('trainer', 'Тренер'), ('admin', 'Администратор')], max_length=20, null=True, verbose_name='Кто отменил')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина отмены')),
                ('price_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clients.client', verbose_name='Клиент')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.session', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneTimeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Дата посещения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('visited', 'Посетил'), ('canceled', 'Отменено')], default='paid', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_visits', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Разовое посещение',
                'verbose_name_plural': 'Разовые посещения',
                'ordering': ['-visit_date', '-created_at'],
                'indexes': [models.Index(fields=['visit_date'], name='idx_one_time_visits_visit_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='chk_sessions_time'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='chk_sessions_capacity'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('client', 'session'), name='unique_client_session_booking'),
        ),
    ]
